services:
  padel:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3964:3003"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
